### ISSUE TITLE
Add wissensschule.de article to press section

### ISSUE THREAD

**Issue by Eldorado234** [ZUKSev/ZUKS-Website#26]
http://www.wissensschule.de/zuks-%C2%AD-zivile-unterstuetzung-im-katastrophenschutz/

**Comment by Eldorado234** [comment]
+StartUp Slam

**Comment by monofox** [comment]
@Eldorado234 : for the StartUp Slam: only the video or also the "general" news from [Rhein-Main-Startups](http://rhein-main-startups.com/2014/12/01/100-gaste-7-startups-1-sieger-team-das-war-der-1-startup-slam-wiesbaden/) and [sensor Wiesbaden](http://www.sensor-wiesbaden.de/wiesbadenrocks-beim-1-startup-slam-spannender-abend-der-guten-ideen-war-ein-gewinn-fuer-alle/) or did i missed any other (written) news in press?

**Comment by Eldorado234** [comment]
I would add the two general articles you've linked too. An even more general article was published by the WK: http://www.wiesbadener-kurier.de/lokales/wiesbaden/nachrichten-wiesbaden/neugruender-stellen-im-wiesbadener-heimathafen-ihre-ideen-vor_14813706.htm. We are not mentioned there, so I wouldn't add this one.
