### ISSUE TITLE
Add materialUp-Link to websites press review

### ISSUE THREAD

**Issue by Quizzer** [ZUKSev/ZUKS-Website#39]
http://www.materialup.com/posts/app-for-organising-volunteers-in-civil-protection

**Comment by Quizzer** [comment]
added label "content"

**Comment by Eldorado234** [comment]
I uploaded the prototoype website to materialup, they just accepted my request. I won't put the link in the press section for this reason.

**Comment by Quizzer** [comment]
I see your point. We just thought it could valorize our website if we add this link. But you are right the press review is not the best place to do so.
